### ISSUE TITLE
bug: Command permissions errors still marked internally as sucessful.

### ISSUE THREAD

**Issue by JABirchall** [skyra-project/skyra#1975]
**Describe the bug**

In example of the lockdown command. By default, the requested permissions of skyra prohibit this command from working.

So when running lockdown, skyra reports a permission error. Once fixing the permissions and running lockdown again, skyra logs that the lock has been released. Indicating that internally Skyra has marked the channel as locked, despite failing to do so because of permission errors.

**To Reproduce**

1. Have skyra in a server with the default requested permissions via the invite.
2. run the lockdown command in a channel
3. See error `DiscordAPIError: Missing Permissions`
4. Add the correct permissions to skyra
5. Run lockdown again
6. See `The lockdown for the channel #channel has been released.`

**Expected behavior**

If the command fails due to a permissions error, the channel should not be marked as locked internally
Also the skyra invite link should include the correct permission for this command to work.

This could effect other commands as well, but haven't tested others.

**Comment by favna** [comment]
I tried to reproduce it by creating a new server, inviting my alt for lockdown check and inviting skyra for locking but when I ran `s!lockdown` in there it worked just fine. Nothing was logged to console nor the production error logs, and the lock was successful. These were the permissions from the invite:

![image](https://user-images.githubusercontent.com/4019718/126899333-73603e63-a535-4764-b0e5-c5be096210f7.png)

Could you review your reproduction steps? Also were you using the latest version of skyra? Because Kyra patched at least 1 bug in the lockdown command a couple of weeks ago.

**Comment by JABirchall** [comment]
> 
> Could you review your reproduction steps? Also were you using the latest version of skyra? Because Kyra patched at least 1 bug in the lockdown command a couple of weeks ago.

I managed to kinda replicate it again??? but in a different way. The bot completely locked up the lockdown command trying lock the channel.

![](https://i.imgur.com/RbfYo5n.png)

This time it didn't log a permission error. But something else has errored out.

**Comment by JABirchall** [comment]
> 
> 
> I tried to reproduce it by creating a new server, inviting my alt for lockdown check and inviting skyra for locking but when I ran `s!lockdown` in there it worked just fine. Nothing was logged to console nor the production error logs, and the lock was successful. These were the permissions from the invite:
> 
> ![image](https://user-images.githubusercontent.com/4019718/126899333-73603e63-a535-4764-b0e5-c5be096210f7.png)
> 
> Could you review your reproduction steps? Also were you using the latest version of skyra? Because Kyra patched at least 1 bug in the lockdown command a couple of weeks ago.

I couldn't replicate the above report, but found a different issue?

Skyra not being able to lift the lockdown after it is locked.

![](https://i.imgur.com/Yrkf6GK.png)

**Comment by kyranet** [comment]
That's because the framework doesn't run commands if the bot cannot send messages, this is common in all of them.

What can be done, though, is that Skyra could give herself permissions to send messages at the same as denying permissions for the everyone role, but it might clutter permissions in the long run.

**Comment by favna** [comment]
Should also note that you can do `s!lockdown unlock ChannelThatsLockedHere` like `s!lockdown unlock #o-o`
