### ISSUE TITLE
request: Optional config delete message after "Skyra, roles XY"

### ISSUE THREAD

**Issue by pwnyprod** [skyra-project/skyra#2225]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

An optional configuration (maybe also in the Backend) to automatically delete the messages (command message and bot response) after the role was applied.

### Desired solution

Acceptance criteria like:
* [ ] bool if the bot command should be deleted
* [ ] bool if the bot response should be deleted
* [ ] duration before the message will be deleted in sec
* [ ] add configuration of these params to the roles tab in skyra frontend (skyra.pw/guilds/XXXXXXX/roles)
* [ ] add a "this message will be deleted after X sec" to the response

### Alternatives considered

Acceptance criteria like:
* [ ] bool if the bot command and the response should be deleted after success
* [ ] hardcode delete duration to 10 sec or something readable like that

### Additional context

Discovered this while users on my guild will use the commands in the same channel the public roles description is in (the users are non techis) 😄 for now i delete this messages on my own 🤣

**Comment by favna** [comment]
I am going to close this because it will never be realized. Part of our plans for Skyra V7 (which you can read here: https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8 ) is removing public roles as they are done now and instead implementing them using Buttons and/or Select Menus. An example of how this might look is Discord's official Pronoun Picker bot: https://support.discord.com/hc/en-us/articles/1500012528941-Pronoun-Picker-Bot-FAQ

![image](https://user-images.githubusercontent.com/4019718/158058154-09bbe055-3300-4fff-9cbe-4129c52f5308.png)


Clicking a role button will give an **ephemeral** reply which only the person clicking can see and disappears automatically after some time. 

![image](https://user-images.githubusercontent.com/4019718/158058157-d7fa7630-1c35-438b-a3bd-7590256acbdb.png)
