### ISSUE TITLE
todo: Deleted User removal.

### ISSUE THREAD

**Issue by Quantumlyy** [skyra-project/skyra#656]
Update leaderboard and other commands that fetch users to automatically remove entries from the db if the user's username is `Deleted User`, or whatever is a valid check for them -Kyra

**Comment by kyranet** [comment]
Since we're removing message-based economy in favour of a RPG module (powered by Nayre), the leaderboards will become local-only. Furthermore, users can easily fake `Deleted User`, so the checks in place would naturally fail.

Also check the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) for more information about the future changes.
